=== MaxDreger92/MatGraph/sdl/config/labware/schemas/labware_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Labware",
  "type": "object",
  "properties": {
    "ordering": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {"type": "string"}
      }
    },
    "brand": {
      "type": "object",
      "properties": {
        "brand": {"type": "string"},
        "brandId": {
          "type": "array",
          "items": {"type": "string"}
        }
      }
    },
    "metadata": {
      "type": "object",
      "properties": {
        "displayName": {"type": "string"},
        "displayCategory": {"type": "string"},
        "displayVolumeUnits": {"type": "string"},
        "tags": {"type": "array", "items": {"type": "string"}}
      }
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "xDimension": {"type": "number"},
        "yDimension": {"type": "number"},
        "zDimension": {"type": "number"}
      }
    },
    "wells": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "depth": {"type": "number"},
          "totalLiquidVolume": {"type": "number"},
          "shape": {"type": "string"},
          "diameter": {"type": "number"},
          "xDimension": {"type": "number"},
          "yDimension": {"type": "number"},
          "x": {"type": "number"},
          "y": {"type": "number"},
          "z": {"type": "number"}
        }
      }
    },
    "groups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "metadata": {
            "type": "object",
            "properties": {
              "wellBottomShape": {"type": "string"}
            }
          },
          "wells": {
            "type": "array",
            "items": {"type": "string"}
          }
        }
      }
    },
    "parameters": {
      "type": "object",
      "properties": {
        "format": {"type": "string"},
        "quirks": {"type": "array", "items": {"type": "string"}},
        "isMagneticModuleCompatible": {"type": "boolean"},
        "loadName": {"type": "string"}
      }
    },
    "namespace": {"type": "string"},
    "version": {"type": "number"},
    "schemaVersion": {"type": "number"},
    "cornerOffsetFromSlot": {
      "type": "object",
      "properties": {
        "x": {"type": "number"},
        "y": {"type": "number"},
        "z": {"type": "number"}
      }
    }
  },
  "required": [
    "ordering",
    "brand",
    "metadata",
    "dimensions",
    "wells",
    "groups",
    "parameters",
    "namespace",
    "version",
    "schemaVersion",
    "cornerOffsetFromSlot"
  ]
}

=== MaxDreger92/MatGraph/sdl/config/labware/sargent_15_reservoir_5750ul.json
{
    "ordering": [
        [
            "A1",
            "B1",
            "C1"
        ],
        [
            "A2",
            "B2",
            "C2"
        ],
        [
            "A3",
            "B3",
            "C3"
        ],
        [
            "A4",
            "B4",
            "C4"
        ],
        [
            "A5",
            "B5",
            "C5"
        ]
    ],
    "brand": {
        "brand": "Sargent",
        "brandId": [
            "Jehad"
        ]
    },
    "metadata": {
        "displayName": "Sargent 15 Reservoir 5750 µL",
        "displayCategory": "reservoir",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127,
        "yDimension": 85,
        "zDimension": 38
    },
    "wells": {
        "A1": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 22.8,
            "y": 63.5,
            "z": 17
        },
        "B1": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 22.8,
            "y": 43.5,
            "z": 17
        },
        "C1": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 22.8,
            "y": 23.5,
            "z": 17
        },
        "A2": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 42.8,
            "y": 63.5,
            "z": 17
        },
        "B2": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 42.8,
            "y": 43.5,
            "z": 17
        },
        "C2": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 42.8,
            "y": 23.5,
            "z": 17
        },
        "A3": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 62.8,
            "y": 63.5,
            "z": 17
        },
        "B3": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 62.8,
            "y": 43.5,
            "z": 17
        },
        "C3": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 62.8,
            "y": 23.5,
            "z": 17
        },
        "A4": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 82.8,
            "y": 63.5,
            "z": 17
        },
        "B4": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 82.8,
            "y": 43.5,
            "z": 17
        },
        "C4": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 82.8,
            "y": 23.5,
            "z": 17
        },
        "A5": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 102.8,
            "y": 63.5,
            "z": 17
        },
        "B5": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 102.8,
            "y": 43.5,
            "z": 17
        },
        "C5": {
            "depth": 21,
            "totalLiquidVolume": 5750,
            "shape": "circular",
            "diameter": 19,
            "x": 102.8,
            "y": 23.5,
            "z": 17
        }
    },
    "groups": [
        {
            "metadata": {
                "wellBottomShape": "flat"
            },
            "wells": [
                "A1",
                "B1",
                "C1",
                "A2",
                "B2",
                "C2",
                "A3",
                "B3",
                "C3",
                "A4",
                "B4",
                "C4",
                "A5",
                "B5",
                "C5"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isMagneticModuleCompatible": false,
        "loadName": "sargent_15_reservoir_5750ul",
        "isTiprack": false
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}

=== MaxDreger92/MatGraph/sdl/config/labware/nis_4_tiprack_1ul.json
{
    "ordering": [
        [
            "A1",
            "B1"
        ],
        [
            "A2",
            "B2"
        ]
    ],
    "brand": {
        "brand": "Nis",
        "brandId": [
            "tool",
            "electrode"
        ]
    },
    "metadata": {
        "displayName": "Nis 4 Tip Rack 1 µL",
        "displayCategory": "tipRack",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127,
        "yDimension": 85,
        "zDimension": 95
    },
    "wells": {
        "A1": {
            "depth": 89.35,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 31.69,
            "y": 64.26,
            "z": 5.65
        },
        "B1": {
            "depth": 89.35,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 31.69,
            "y": 20.75,
            "z": 5.65
        },
        "A2": {
            "depth": 89.35,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 95.25,
            "y": 64.26,
            "z": 5.65
        },
        "B2": {
            "depth": 89.35,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 95.25,
            "y": 20.75,
            "z": 5.65
        }
    },
    "groups": [
        {
            "metadata": {},
            "wells": [
                "A1",
                "B1",
                "A2",
                "B2"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "tipLength": 89.35,
        "isMagneticModuleCompatible": false,
        "loadName": "nis_4_tiprack_1ul",
        "isTiprack": true
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}

=== MaxDreger92/MatGraph/sdl/config/labware/autodial_25_reservoir_4620ul.json
{
    "ordering": [
        [
            "A1",
            "B1",
            "C1",
            "D1",
            "E1"
        ],
        [
            "A2",
            "B2",
            "C2",
            "D2",
            "E2"
        ],
        [
            "A3",
            "B3",
            "C3",
            "D3",
            "E3"
        ],
        [
            "A4",
            "B4",
            "C4",
            "D4",
            "E4"
        ],
        [
            "A5",
            "B5",
            "C5",
            "D5",
            "E5"
        ]
    ],
    "brand": {
        "brand": "AUTODIAL",
        "brandId": [
            "Daniel"
        ]
    },
    "metadata": {
        "displayName": "AUTODIAL 25 Reservoir 4620 µL",
        "displayCategory": "reservoir",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127.75,
        "yDimension": 85.5,
        "zDimension": 51
    },
    "wells": {
        "A1": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 34.38,
            "y": 72.25,
            "z": 21.5
        },
        "B1": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 34.38,
            "y": 57.25,
            "z": 21.5
        },
        "C1": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 34.38,
            "y": 42.25,
            "z": 21.5
        },
        "D1": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 34.38,
            "y": 27.25,
            "z": 21.5
        },
        "E1": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 34.38,
            "y": 12.25,
            "z": 21.5
        },
        "A2": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 49.38,
            "y": 72.25,
            "z": 21.5
        },
        "B2": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 49.38,
            "y": 57.25,
            "z": 21.5
        },
        "C2": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 49.38,
            "y": 42.25,
            "z": 21.5
        },
        "D2": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 49.38,
            "y": 27.25,
            "z": 21.5
        },
        "E2": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 49.38,
            "y": 12.25,
            "z": 21.5
        },
        "A3": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 64.38,
            "y": 72.25,
            "z": 21.5
        },
        "B3": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 64.38,
            "y": 57.25,
            "z": 21.5
        },
        "C3": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 64.38,
            "y": 42.25,
            "z": 21.5
        },
        "D3": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 64.38,
            "y": 27.25,
            "z": 21.5
        },
        "E3": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 64.38,
            "y": 12.25,
            "z": 21.5
        },
        "A4": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 79.38,
            "y": 72.25,
            "z": 21.5
        },
        "B4": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 79.38,
            "y": 57.25,
            "z": 21.5
        },
        "C4": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 79.38,
            "y": 42.25,
            "z": 21.5
        },
        "D4": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 79.38,
            "y": 27.25,
            "z": 21.5
        },
        "E4": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 79.38,
            "y": 12.25,
            "z": 21.5
        },
        "A5": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 94.38,
            "y": 72.25,
            "z": 21.5
        },
        "B5": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 94.38,
            "y": 57.25,
            "z": 21.5
        },
        "C5": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 94.38,
            "y": 42.25,
            "z": 21.5
        },
        "D5": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 94.38,
            "y": 27.25,
            "z": 21.5
        },
        "E5": {
            "depth": 29.5,
            "totalLiquidVolume": 4620,
            "shape": "circular",
            "diameter": 14,
            "x": 94.38,
            "y": 12.25,
            "z": 21.5
        }
    },
    "groups": [
        {
            "metadata": {
                "wellBottomShape": "flat"
            },
            "wells": [
                "A1",
                "B1",
                "C1",
                "D1",
                "E1",
                "A2",
                "B2",
                "C2",
                "D2",
                "E2",
                "A3",
                "B3",
                "C3",
                "D3",
                "E3",
                "A4",
                "B4",
                "C4",
                "D4",
                "E4",
                "A5",
                "B5",
                "C5",
                "D5",
                "E5"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isMagneticModuleCompatible": false,
        "loadName": "autodial_25_reservoir_4620ul",
        "isTiprack": false
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}

=== MaxDreger92/MatGraph/sdl/config/labware/nis_8_reservoir_25000ul.json
{
    "ordering": [
        [
            "A1",
            "B1"
        ],
        [
            "A2",
            "B2"
        ],
        [
            "A3",
            "B3"
        ],
        [
            "A4",
            "B4"
        ]
    ],
    "brand": {
        "brand": "Nis",
        "brandId": []
    },
    "metadata": {
        "displayName": "Nis 8 Reservoir 25000 µL",
        "displayCategory": "reservoir",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127.75,
        "yDimension": 85.5,
        "zDimension": 60.4
    },
    "wells": {
        "A1": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 16.34,
            "y": 65.25,
            "z": 3.4
        },
        "B1": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 16.34,
            "y": 20.25,
            "z": 3.4
        },
        "A2": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 48.01,
            "y": 65.25,
            "z": 3.4
        },
        "B2": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 48.01,
            "y": 20.25,
            "z": 3.4
        },
        "A3": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 79.68,
            "y": 65.25,
            "z": 3.4
        },
        "B3": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 79.68,
            "y": 20.25,
            "z": 3.4
        },
        "A4": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 111.35,
            "y": 65.25,
            "z": 3.4
        },
        "B4": {
            "depth": 57,
            "totalLiquidVolume": 25000,
            "shape": "circular",
            "diameter": 25,
            "x": 111.35,
            "y": 20.25,
            "z": 3.4
        }
    },
    "groups": [
        {
            "metadata": {
                "wellBottomShape": "flat"
            },
            "wells": [
                "A1",
                "B1",
                "A2",
                "B2",
                "A3",
                "B3",
                "A4",
                "B4"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isMagneticModuleCompatible": false,
        "loadName": "nis_8_reservoir_25000ul",
        "isTiprack": false
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}

=== MaxDreger92/MatGraph/sdl/config/labware/nis_15_wellplate_3895ul.json
{
    "ordering": [
        [
            "A1",
            "B1",
            "C1"
        ],
        [
            "A2",
            "B2",
            "C2"
        ],
        [
            "A3",
            "B3",
            "C3"
        ],
        [
            "A4",
            "B4",
            "C4"
        ],
        [
            "A5",
            "B5",
            "C5"
        ]
    ],
    "brand": {
        "brand": "Nis",
        "brandId": []
    },
    "metadata": {
        "displayName": "Nis 15 Well Plate 3895 µL",
        "displayCategory": "wellPlate",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127,
        "yDimension": 85,
        "zDimension": 100
    },
    "wells": {
        "A1": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 12.7,
            "y": 70.83,
            "z": 69
        },
        "B1": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 12.7,
            "y": 42.5,
            "z": 69
        },
        "C1": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 12.7,
            "y": 14.17,
            "z": 69
        },
        "A2": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 38.1,
            "y": 70.83,
            "z": 69
        },
        "B2": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 38.1,
            "y": 42.5,
            "z": 69
        },
        "C2": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 38.1,
            "y": 14.17,
            "z": 69
        },
        "A3": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 63.5,
            "y": 70.83,
            "z": 69
        },
        "B3": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 63.5,
            "y": 42.5,
            "z": 69
        },
        "C3": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 63.5,
            "y": 14.17,
            "z": 69
        },
        "A4": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 88.9,
            "y": 70.83,
            "z": 69
        },
        "B4": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 88.9,
            "y": 42.5,
            "z": 69
        },
        "C4": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 88.9,
            "y": 14.17,
            "z": 69
        },
        "A5": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 114.3,
            "y": 70.83,
            "z": 69
        },
        "B5": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 114.3,
            "y": 42.5,
            "z": 69
        },
        "C5": {
            "depth": 31,
            "totalLiquidVolume": 3895,
            "shape": "circular",
            "diameter": 20,
            "x": 114.3,
            "y": 14.17,
            "z": 69
        }
    },
    "groups": [
        {
            "metadata": {
                "wellBottomShape": "v"
            },
            "wells": [
                "A1",
                "B1",
                "C1",
                "A2",
                "B2",
                "C2",
                "A3",
                "B3",
                "C3",
                "A4",
                "B4",
                "C4",
                "A5",
                "B5",
                "C5"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isMagneticModuleCompatible": false,
        "loadName": "nis_15_wellplate_3895ul",
        "isTiprack": false
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}

=== MaxDreger92/MatGraph/sdl/config/labware/nis_2_wellplate_30000ul.json
{
    "ordering": [
        [
            "A1"
        ],
        [
            "A2"
        ]
    ],
    "brand": {
        "brand": "Nis",
        "brandId": []
    },
    "metadata": {
        "displayName": "Nis 2 Well Plate 30000 µL",
        "displayCategory": "wellPlate",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127,
        "yDimension": 85,
        "zDimension": 104
    },
    "wells": {
        "A1": {
            "depth": 24,
            "totalLiquidVolume": 30000,
            "shape": "rectangular",
            "xDimension": 25,
            "yDimension": 59.7,
            "x": 35.3,
            "y": 42,
            "z": 80
        },
        "A2": {
            "depth": 24,
            "totalLiquidVolume": 30000,
            "shape": "rectangular",
            "xDimension": 25,
            "yDimension": 59.7,
            "x": 91.7,
            "y": 42,
            "z": 80
        }
    },
    "groups": [
        {
            "metadata": {
                "wellBottomShape": "flat"
            },
            "wells": [
                "A1",
                "A2"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isMagneticModuleCompatible": false,
        "loadName": "nis_2_wellplate_30000ul",
        "isTiprack": false
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}

=== MaxDreger92/MatGraph/sdl/config/labware/nistall_4_tiprack_1ul.json
{
    "ordering": [
        [
            "A1",
            "B1"
        ],
        [
            "A2",
            "B2"
        ]
    ],
    "brand": {
        "brand": "nis_tall",
        "brandId": [
            "electrodeHolder_tall"
        ]
    },
    "metadata": {
        "displayName": "Nis_tall 4 Tip Rack 1 µL",
        "displayCategory": "tipRack",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127.75,
        "yDimension": 85.5,
        "zDimension": 117
    },
    "wells": {
        "A1": {
            "depth": 94,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 31.75,
            "y": 64.25,
            "z": 26
        },
        "B1": {
            "depth": 94,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 31.75,
            "y": 20.75,
            "z": 26
        },
        "A2": {
            "depth": 94,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 95.25,
            "y": 64.25,
            "z": 26
        },
        "B2": {
            "depth": 94,
            "totalLiquidVolume": 1,
            "shape": "circular",
            "diameter": 8,
            "x": 95.25,
            "y": 20.75,
            "z": 26
        }
    },
    "groups": [
        {
            "metadata": {},
            "wells": [
                "A1",
                "B1",
                "A2",
                "B2"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "tipLength": 94,
        "isMagneticModuleCompatible": false,
        "loadName": "nistall_4_tiprack_1ul",
        "isTiprack": true
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}
