=== MaxDreger92/MatGraph/sdl/config/labware/schemas/labware_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Labware",
  "type": "object",
  "properties": {
    "ordering": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {"type": "string"}
      }
    },
    "brand": {
      "type": "object",
      "properties": {
        "brand": {"type": "string"},
        "brandId": {
          "type": "array",
          "items": {"type": "string"}
        }
      }
    },
    "metadata": {
      "type": "object",
      "properties": {
        "displayName": {"type": "string"},
        "displayCategory": {"type": "string"},
        "displayVolumeUnits": {"type": "string"},
        "tags": {"type": "array", "items": {"type": "string"}}
      }
    },
    "dimensions": {
      "type": "object",
      "properties": {
        "xDimension": {"type": "number"},
        "yDimension": {"type": "number"},
        "zDimension": {"type": "number"}
      }
    },
    "wells": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "depth": {"type": "number"},
          "totalLiquidVolume": {"type": "number"},
          "shape": {"type": "string"},
          "diameter": {"type": "number"},
          "xDimension": {"type": "number"},
          "yDimension": {"type": "number"},
          "x": {"type": "number"},
          "y": {"type": "number"},
          "z": {"type": "number"}
        }
      }
    },
    "groups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "metadata": {
            "type": "object",
            "properties": {
              "wellBottomShape": {"type": "string"}
            }
          },
          "wells": {
            "type": "array",
            "items": {"type": "string"}
          }
        }
      }
    },
    "parameters": {
      "type": "object",
      "properties": {
        "format": {"type": "string"},
        "quirks": {"type": "array", "items": {"type": "string"}},
        "isMagneticModuleCompatible": {"type": "boolean"},
        "loadName": {"type": "string"}
      }
    },
    "namespace": {"type": "string"},
    "version": {"type": "number"},
    "schemaVersion": {"type": "number"},
    "cornerOffsetFromSlot": {
      "type": "object",
      "properties": {
        "x": {"type": "number"},
        "y": {"type": "number"},
        "z": {"type": "number"}
      }
    }
  },
  "required": [
    "ordering",
    "brand",
    "metadata",
    "dimensions",
    "wells",
    "groups",
    "parameters",
    "namespace",
    "version",
    "schemaVersion",
    "cornerOffsetFromSlot"
  ]
}

=== MaxDreger92/MatGraph/sdl/config/labware/tlg_1_reservoir_50000ul.json
{
    "ordering": [
        [
            "A1"
        ]
    ],
    "brand": {
        "brand": "TLG",
        "brandId": [
            "50mlBeaker"
        ]
    },
    "metadata": {
        "displayName": "TLG 1 Reservoir 50000 µL",
        "displayCategory": "reservoir",
        "displayVolumeUnits": "µL",
        "tags": []
    },
    "dimensions": {
        "xDimension": 127,
        "yDimension": 85,
        "zDimension": 58
    },
    "wells": {
        "A1": {
            "depth": 56,
            "totalLiquidVolume": 50000,
            "shape": "circular",
            "diameter": 38.6,
            "x": 63.5,
            "y": 42.5,
            "z": 2
        }
    },
    "groups": [
        {
            "metadata": {
                "wellBottomShape": "flat"
            },
            "wells": [
                "A1"
            ]
        }
    ],
    "parameters": {
        "format": "irregular",
        "quirks": [],
        "isMagneticModuleCompatible": false,
        "loadName": "tlg_1_reservoir_50000ul",
        "isTiprack": false
    },
    "namespace": "custom_beta",
    "version": 1,
    "schemaVersion": 2,
    "cornerOffsetFromSlot": {
        "x": 0,
        "y": 0,
        "z": 0
    }
}
